extend type Query {
  """
  ✨ Look up a single `Log` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  log(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Log_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Log_FirstRow
  ): Log @fdc_generated(from: "Log", purpose: QUERY_SINGLE)
  """
  ✨ List `Log` objects in the table, optionally filtered by `where` conditions.
  """
  logs(
    """
    Filter condition to narrow down the query results.
    """
    where: Log_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Log_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Log!]! @fdc_generated(from: "Log", purpose: QUERY_MULTIPLE)
}
