type Log @table {
  # FIXME: This would work if we used Firebase Auth UID as the user ID. Everything is automatic
  # `@default(expr: "auth.uid")` sets it to Firebase Auth UID during insert and upsert.
  userID: String! @default(expr: "auth.uid")

  # FIXME: The analisis would probably output some list of probabilities for emotions
  # For know a string of the emotion is enough for the MVP
  emotion: String! @col(dataType: "varchar(50)")
  
  date: Date! @default(expr: "request.time")
}